### ISSUE TITLE
Writing of results in single parameter fits with constrained coefficients

### ISSUE THREAD

**Issue by LucaMantani** [LHCfitNikhef/smefit_release#117]
Something strange is happening when writing the fit_results.json with single parameter fits and constrained coefficients.

E.g. with the runcard below
```
# Input YAML configurations for SMEFiT code

result_ID: LEP_indiv_lin

# absolute path where results are stored
result_path: results

# path to common data
data_path: /Users/luca/Applications/smefit_database/commondata

# path to theory tables, default same as data path
theory_path: /Users/luca/Applications/smefit_database/theory

# pQCD order (LO or NLO)
order: NLO

use_theory_covmat: True

use_t0: True

# SMEFT Expansion Order (NHO = Lambda^-2 , HO = Lambda^-4)
use_quad: False

# Set parameter bounds to previous SCAN result
bounds: Null

n_samples: 10000


# Datasets to include
datasets:

  - {name: LEP1_EWPOs_2006, order: LO}
  - {name: LEP_Bhabha_2013, order: LO}
  - {name: LEP_Brw_2013, order: LO}
  - {name: LEP_alphaEW, order: LO}
  - {name: LEP_eeWW_182GeV, order: LO}
  - {name: LEP_eeWW_189GeV, order: LO}
  - {name: LEP_eeWW_198GeV, order: LO}
  - {name: LEP_eeWW_206GeV, order: LO}




# Coefficients to fit
coefficients:
  # Free params
  OpqMi: { 'min': -1, 'max': 1 }
  O3pq: { 'min': -1, 'max': 1 }
  
  ## To fix ##
  OpQM: {'constrain': [{'OpqMi': 1}], 'min': -2, 'max': 2 }
  O3pQ3: {'constrain': [{'O3pq': 1}], 'min': -1, 'max': 1 }

single_parameter_fits: true

rot_to_fit_basis: null

```

What I observe is that instead of writing OpqMi and O3pq, it writes OpQM and O3pQ3. My suspicion is that it is writing the one that comes first in alphabetical order?
